networks:
  messaggio:
    driver: bridge

services:
  # todo golang app
  db:
    image: postgres:16.3-alpine
    restart: always
    ports:
      - 127.0.0.1:${DB_PORT}:5432
    networks:
      - messaggio
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-data:/var/lib/postgresql/data
  # todo kafka